<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use AppBundle\Entity\Article;
use Doctrine\ORM\Tools\Pagination\Paginator;


class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function getArticlesPaginated($page)
    {
        $qb = $this->createQueryBuilder('a')->where('a.date <= :now')->setParameter(':now', new \DateTime());
        $query = $qb->getQuery();
        $query
            // On définit l'article à partir duquel commencer la liste
            ->setFirstResult(($page - 1) * Article::NUM_ITEMS)
            // Ainsi que le nombre d'annonce à afficher sur une page
            ->setMaxResults(Article::NUM_ITEMS);
        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        return new Paginator($query, true);
    }

    public function findAllAsc()
    {
        return $this->findBy(array(), array('date' => 'ASC'));
    }

    public function countAll()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
