<?php

namespace AppBundle\Repository;

/**
 * TaxrefProtegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefProtegeRepository extends \Doctrine\ORM\EntityRepository
{
}
